[build-system]
requires = ['setuptools', 'cython <3, >=0.21']
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-all = [
    "(apt-get update && apt-get install --yes wget) || yum install -y wget zlib libgfortran || brew install wget",
    "wget https://github.com/mmghannam/scip/releases/download/v8.0.3/libscip-centos.zip -O scip.zip",
    "unzip scip.zip",
    "mv scip_install scip"
    ]
environment = { SCIPOPTDIR="$(pwd)/scip", LD_LIBRARY_PATH="$(pwd)/scip/lib:LD_LIBRARY_PATH", DYLD_LIBRARY_PATH="$(pwd)/scip/lib:$DYLD_LIBRARY_PATH", PATH="$(pwd)/scip/bin:$PATH", PKG_CONFIG_PATH="$(pwd)/scip/lib/pkgconfig:$PKG_CONFIG_PATH"}


[tool.cibuildwheel.macos]
before-all = [
    "brew install wget zlib gcc",
    "wget https://github.com/mmghannam/scip/releases/download/v8.0.3/libscip-macos.zip -O scip.zip",
    "unzip scip.zip",
    "mv scip_install scip"
    ]
environment = { SCIPOPTDIR="$(pwd)/scip", LD_LIBRARY_PATH="$(pwd)/scip/lib:LD_LIBRARY_PATH", DYLD_LIBRARY_PATH="$(pwd)/scip/lib:$DYLD_LIBRARY_PATH", PATH="$(pwd)/scip/bin:$PATH", PKG_CONFIG_PATH="$(pwd)/scip/lib/pkgconfig:$PKG_CONFIG_PATH"}


[tool.cibuildwheel.windows]
before-all = [
    "choco install 7zip wget",
    "wget https://github.com/mmghannam/scip/releases/download/v8.0.3/libscip-windows.zip -O scip.zip",
    "\"C:\\Program Files\\7-Zip\\7z.exe\" x \"scip.zip\" -o\"scip-test\"",
    "mv .\\scip-test\\scip_install .\\test",
    "mv .\\test .\\scip"
]
environment = { SCIPOPTDIR="$(pwd)\\scip"}
