[build-system]
requires = ['setuptools', 'cython <3, >=0.21']
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-all = [
    "(apt-get update && apt-get install --yes wget) || yum install -y wget || brew install wget",
    "wget https://github.com/mmghannam/scip/releases/download/v8.0.3/libscip-ubuntu.zip -O scip.zip",
    "unzip scip.zip",
    "unzip upload.zip",
    "mv home/runner/work/scip/scip/ipopt/ scip"
    ]
build-frontend = "build"
manylinux-x86_64-image = "manylinux_2_28"
environment = { SCIPOPTDIR="$(pwd)/scip", LD_LIBRARY_PATH="$(pwd)/scip/lib:LD_LIBRARY_PATH", DYLD_LIBRARY_PATH="$(pwd)/scip/lib:$DYLD_LIBRARY_PATH", PATH="$(pwd)/scip/bin:$PATH", PKG_CONFIG_PATH="$(pwd)/scip/lib/pkgconfig:$PKG_CONFIG_PATH"}