name: Release PyPI Package

on:
  release:
    branches: [master]
    types: [published]
    tags:
      - v*.*.*           # release events to vx.y.z

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (SCIPOptSuite)
        run: |
          wget --quiet --no-check-certificate https://scipopt.org/download/release/SCIPOptSuite-${{ env.version }}-Linux-ubuntu.deb
          sudo apt-get update && sudo apt install -y ./SCIPOptSuite-${{ env.version }}-Linux-ubuntu.deb

      - name: Setup python 3
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'

      - name: Prepare python environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel cython networkx pytest-cov build

      - name: Build package
        run: |
          python -m build --no-isolation --outdir dist/

      - name: Generate documentation
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          ./generate-docs.sh "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          packages-dir: dist/


