name: test build

on: [push]

jobs:
  Package-build:
    runs-on: ubuntu-18.04
    env:
      version: 7.0.3
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.9'

      - name: SCIPOptSuite installation
        run: |
          wget --quiet --no-check-certificate https://scipopt.org/download/release/SCIPOptSuite-${{ env.version }}-Linux-ubuntu.deb
          sudo apt-get update && sudo apt install -y ./SCIPOptSuite-${{ env.version }}-Linux-ubuntu.deb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel cython networkx pytest-cov build

      - name: Build package
        run: |
          python -m build --no-isolation
