name: test build

on: [push]

jobs:
  Package-build:
    runs-on: ubuntu-18.04
    env:
      version: 7.0.3
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'

      - name: info
        run: |
          env | sort

